language: node_js
node_js:
  - 11.10.1
cache: yarn
notifications:
  email: false
git:
  depth: 3
branches:
  only:
    - master
before_install:
  # We update yarn, because Travis uses an outdated version that produces
  # error messages in our integration tests.
  # See https://github.com/travis-ci/travis-ci/issues/9445.
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
script:
  - yarn lint
  - yarn test
  - yarn build
  - yarn test:e2e
