language: node_js
node_js:
  - 11.10.1
cache: yarn
notifications:
  email: false
git:
  depth: 3
branches:
  only:
    - master
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
script:
  - yarn lint
  - yarn test
  - yarn build
  - yarn test:integration
